# Generated by Django 5.1.5 on 2025-02-06 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
